main_port = 8080
control_port = 27888

# Tracing configuration
# Format options: "pretty", "compact", "json"
# - pretty: human-readable multi-line format (best for development)
# - compact: single-line format (default)
# - json: structured JSON format (best for production/log aggregation)
[tracing]
format = "pretty"
level = "info"    # Options: "trace", "debug", "info", "warn", "error"
